USE [master]
GO
/****** Object:  Database [Landerist]    Script Date: 20/06/2023 11:52:48 ******/
CREATE DATABASE [Landerist]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Landerist', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Landerist.mdf' , SIZE = 6955008KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Landerist_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Landerist_log.ldf' , SIZE = 5120000KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Landerist] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Landerist].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Landerist] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Landerist] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Landerist] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Landerist] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Landerist] SET ARITHABORT OFF 
GO
ALTER DATABASE [Landerist] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Landerist] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Landerist] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Landerist] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Landerist] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Landerist] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Landerist] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Landerist] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Landerist] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Landerist] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Landerist] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Landerist] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Landerist] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Landerist] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Landerist] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Landerist] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Landerist] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Landerist] SET RECOVERY FULL 
GO
ALTER DATABASE [Landerist] SET  MULTI_USER 
GO
ALTER DATABASE [Landerist] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Landerist] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Landerist] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Landerist] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Landerist] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Landerist] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Landerist', N'ON'
GO
ALTER DATABASE [Landerist] SET QUERY_STORE = OFF
GO
USE [Landerist]
GO
/****** Object:  Table [dbo].[CNIG]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CNIG](
	[the_geom] [geography] NOT NULL,
	[customid] [int] IDENTITY(10000,1) NOT NULL,
	[inspireid] [nvarchar](50) NOT NULL,
	[natcode] [varchar](50) NOT NULL,
	[nameunit] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_CNIG] PRIMARY KEY CLUSTERED 
(
	[customid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COUNTRIES]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COUNTRIES](
	[the_geom] [geography] NOT NULL,
	[iso_a3] [nchar](10) NOT NULL,
 CONSTRAINT [PK_COUNTRIES] PRIMARY KEY CLUSTERED 
(
	[iso_a3] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ES_LISTINGS]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ES_LISTINGS](
	[guid] [char](64) NOT NULL,
	[listingStatus] [nvarchar](50) NOT NULL,
	[listingDate] [datetime] NULL,
	[unlistingDate] [datetime] NULL,
	[operation] [nvarchar](50) NOT NULL,
	[propertyType] [nvarchar](50) NOT NULL,
	[propertySubtype] [nvarchar](50) NULL,
	[priceAmount] [float] NULL,
	[priceCurrency] [nvarchar](10) NULL,
	[description] [nvarchar](max) NULL,
	[dataSourceName] [nvarchar](500) NULL,
	[dataSourceGuid] [nvarchar](500) NULL,
	[dataSourceUpdate] [datetime] NULL,
	[dataSourceUrl] [nvarchar](max) NULL,
	[contactName] [nvarchar](500) NULL,
	[contactPhone] [nvarchar](500) NULL,
	[contactEmail] [nvarchar](500) NULL,
	[contactUrl] [nvarchar](max) NULL,
	[contactOther] [nvarchar](500) NULL,
	[address] [nvarchar](500) NULL,
	[lauId] [varchar](10) NULL,
	[latitude] [float] NULL,
	[longitude] [float] NULL,
	[locationIsAccurate] [bit] NULL,
	[cadastralReference] [nvarchar](500) NULL,
	[propertySize] [float] NULL,
	[landSize] [float] NULL,
	[constructionYear] [smallint] NULL,
	[constructionStatus] [nvarchar](50) NULL,
	[floors] [smallint] NULL,
	[floor] [nvarchar](500) NULL,
	[bedrooms] [smallint] NULL,
	[bathrooms] [smallint] NULL,
	[parkings] [smallint] NULL,
	[terrace] [bit] NULL,
	[garden] [bit] NULL,
	[garage] [bit] NULL,
	[motorbikeGarage] [bit] NULL,
	[pool] [bit] NULL,
	[lift] [bit] NULL,
	[disabledAccess] [bit] NULL,
	[storageRoom] [bit] NULL,
	[furnished] [bit] NULL,
	[nonFurnished] [bit] NULL,
	[heating] [bit] NULL,
	[airConditioning] [bit] NULL,
	[petsAllowed] [bit] NULL,
	[securitySystems] [bit] NULL,
 CONSTRAINT [PK_ES_LISTINGS] PRIMARY KEY CLUSTERED 
(
	[guid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ES_MEDIA]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ES_MEDIA](
	[listingGuid] [nvarchar](100) NOT NULL,
	[mediaType] [nvarchar](50) NULL,
	[title] [nvarchar](500) NULL,
	[url] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [ClusteredIndex-20230422-102012]    Script Date: 20/06/2023 11:52:48 ******/
CREATE CLUSTERED INDEX [ClusteredIndex-20230422-102012] ON [dbo].[ES_MEDIA]
(
	[listingGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVALID_IMAGES]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVALID_IMAGES](
	[DateInsert] [datetime] NOT NULL,
	[UriHash] [char](64) NOT NULL,
 CONSTRAINT [PK_DISCARDED_IMAGES] PRIMARY KEY CLUSTERED 
(
	[UriHash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LAU]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LAU](
	[the_geom] [geography] NOT NULL,
	[gisco_id] [varchar](50) NOT NULL,
	[lau_id] [varchar](50) NOT NULL,
	[lau_name] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_LAU] PRIMARY KEY CLUSTERED 
(
	[gisco_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOGS]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGS](
	[IdLog] [bigint] IDENTITY(1000000,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[LogKey] [nvarchar](50) NOT NULL,
	[Source] [nvarchar](max) NOT NULL,
	[Text] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_TABLAGOOLZOOMLOG] PRIMARY KEY CLUSTERED 
(
	[IdLog] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAGES]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAGES](
	[Host] [nvarchar](200) NOT NULL,
	[Uri] [nvarchar](max) NOT NULL,
	[UriHash] [char](64) NOT NULL,
	[Inserted] [datetime] NOT NULL,
	[Updated] [datetime] NULL,
	[HttpStatusCode] [smallint] NULL,
	[ResponseBodyText] [nvarchar](max) NULL,
	[IsListing] [bit] NULL,
 CONSTRAINT [PK_PAGES] PRIMARY KEY CLUSTERED 
(
	[UriHash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIMERS]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIMERS](
	[IdTimer] [bigint] IDENTITY(1000000,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[TimerKey] [varchar](50) NOT NULL,
	[Source] [nvarchar](max) NOT NULL,
	[Milliseconds] [float] NOT NULL,
 CONSTRAINT [PK_TIMERS] PRIMARY KEY CLUSTERED 
(
	[IdTimer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VALID_IMAGES]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VALID_IMAGES](
	[DateInsert] [datetime] NOT NULL,
	[UriHash] [char](64) NOT NULL,
 CONSTRAINT [PK_VALID_IMAGES] PRIMARY KEY CLUSTERED 
(
	[UriHash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WEBSITES]    Script Date: 20/06/2023 11:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WEBSITES](
	[MainUri] [nvarchar](max) NOT NULL,
	[Host] [nvarchar](200) NOT NULL,
	[LanguageCode] [nvarchar](10) NOT NULL,
	[CountryCode] [nvarchar](10) NOT NULL,
	[RobotsTxt] [text] NULL,
	[IpAddress] [nvarchar](50) NULL,
	[HttpStatusCode] [smallint] NULL,
 CONSTRAINT [PK_WEBSITES] PRIMARY KEY CLUSTERED 
(
	[Host] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO
/****** Object:  Index [SpatialIndex-the_geom]    Script Date: 20/06/2023 11:52:48 ******/
CREATE SPATIAL INDEX [SpatialIndex-the_geom] ON [dbo].[CNIG]
(
	[the_geom]
)USING  GEOGRAPHY_AUTO_GRID 
WITH (
CELLS_PER_OBJECT = 16, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO
/****** Object:  Index [SpatialIndex-the_geom]    Script Date: 20/06/2023 11:52:48 ******/
CREATE SPATIAL INDEX [SpatialIndex-the_geom] ON [dbo].[COUNTRIES]
(
	[the_geom]
)USING  GEOGRAPHY_GRID 
WITH (GRIDS =(LEVEL_1 = MEDIUM,LEVEL_2 = MEDIUM,LEVEL_3 = MEDIUM,LEVEL_4 = MEDIUM), 
CELLS_PER_OBJECT = 16, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO
/****** Object:  Index [SpatialIndex-the_geom]    Script Date: 20/06/2023 11:52:48 ******/
CREATE SPATIAL INDEX [SpatialIndex-the_geom] ON [dbo].[LAU]
(
	[the_geom]
)USING  GEOGRAPHY_AUTO_GRID 
WITH (
CELLS_PER_OBJECT = 16, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Landerist] SET  READ_WRITE 
GO
