<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>landerist_tests.Program</StartupObject>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\landerist_application\landerist_application.csproj" />
    <ProjectReference Include="..\landerist_domain\landerist_domain.csproj" />
    <ProjectReference Include="..\landerist_infrastructure\landerist_infrastructure.csproj" />
    <ProjectReference Include="..\landerist_orels\landerist_orels.csproj" />
  </ItemGroup>

</Project>
