<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Com.Bekijkhet.RobotsTxt" Version="1.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Google.Cloud.AIPlatform.V1" Version="3.70.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.14.0" />
    <PackageReference Include="Louw.SitemapParser" Version="0.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="OpenAI-DotNet" Version="8.8.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Newtonsoft.Json.Schema" Version="4.0.1" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="4.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.5" />
    <PackageReference Include="PuppeteerSharp" Version="24.40.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\landerist_application\landerist_application.csproj" />
    <ProjectReference Include="..\landerist_domain\landerist_domain.csproj" />
    <ProjectReference Include="..\landerist_orels\landerist_orels.csproj" />
  </ItemGroup>

</Project>