<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Com.Bekijkhet.RobotsTxt" Version="1.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="PuppeteerSharp" Version="24.40.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\landerist_application\landerist_application.csproj" />
    <ProjectReference Include="..\landerist_domain\landerist_domain.csproj" />
  </ItemGroup>

</Project>